bootJar {
    enabled = true
}

jar {
    enabled = false
}

base.archivesName = 'yurend'
version = '25.50.0'

dependencies {
    implementation(project(":domain"))
    implementation(project(":application"))
    implementation(project(":infrastructure"))

    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
}